---
- hosts: ubuntu
  user: sp00552206@autoai.com
  sudo: yes
  #become_user: sp00552206@autoai.com
  #become_method: sudo
  vars:
   testpath: "{{ tpath }}"
  tasks:
   - name: directory creation
     file:
       path: /etc/{{ testpath }}
       state: directory
